### ISSUE TITLE
How to train and validate the model?

### ISSUE THREAD

**Issue by Coding511** [Sreyan88/MMER#3]
Dear author please guide how to use this model for reproducing the results?
I have cloned the repo in my device.
Now what steps need to follow for training in spyder?

**Comment by Sreyan88** [comment]
Hello! Thank You for your interest. You can follow the steps in our repo. Also, we will soon update our repo with some changes by end of the week so you might want to wait too! @ramaneswaran would also be happy to help if you are stuck somewhere in the instructions.

**Comment by Coding511** [comment]
@Sreyan88 @ramaneswaran I want to run the model to reproduce your results on IEMOCAP.
The instructions are for the shell script. I am using the python editor Spyder; then how to run this?

**Comment by noadore** [comment]
How to solve this report error
![image](https://user-images.githubusercontent.com/96336371/229291342-2fc6f300-6df0-4df2-acfa-74a31bc8bb97.png)
Not consistent for files with missing code per run.Can you help me .thank you.

**Comment by Sreyan88** [comment]
@Utkarsh4430 can you please update our latest code with instructions? Thank You!

**Comment by Sreyan88** [comment]
Hi @Coding511 ,

We will release our latest code with better results in 1-2 days. Thank You for your patience!

**Comment by Coding511** [comment]
@Sreyan88 when will that code out?
Please write in pytorch and which could be run on local machine.

**Comment by Sreyan88** [comment]
Extremely sorry for the delay in response. Our paper has been accepted to InterSpeech 2023, and we have pushed new code with improved performance. Please let us know of any bugs that exist.
