### ISSUE TITLE
Unable to install the necessary dependencies in requirements.txt file

### ISSUE THREAD

**Issue by Miles762** [Sreyan88/MMER#7]
I am trying to run the given code of your paper but despite of creating a new conda environment based on requirements.txt file, the environment is unable to install the required dependencies as a result of which run.sh is not executing. Please help me resolve this issue.
![Error_screenshot](https://github.com/Sreyan88/MMER/assets/96391354/153d6607-7781-4e43-88dc-6556fd9c8c9b)

**Comment by Sreyan88** [comment]
Hi @Miles762 ,

Can you try making your conda environment independently and then just do `pip install -r requirements.txt` after activating the conda environment?

**Comment by Miles762** [comment]
Thank for responding instantly, I created the conda environement independently and also executed the code pip install -r requirements.txt, this resulted in fairseq==0.10.2 not installing, please look into this issue.
![Error_ss2](https://github.com/Sreyan88/MMER/assets/96391354/00e48477-9667-4c31-ab98-afd68e02d245)

**Comment by Miles762** [comment]
I changed the versions of many libraries and eventually all the libraries in requirements.txt downloaded.
